import "./globals.css";
import Navbar from "./components/Navbar";
import { Nunito } from "next/font/google";
import { ShowProvider } from "./context/ShowContext";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Banda Anistia",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/anistiaLogoTransparente.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body className={`${nunito.className} bg-zinc-700 text-white antialiased vsc-initialized`}>
        <Navbar />
        <ShowProvider>
          <main className="h-screen flex justify-center mt-32 items-center sm:items-start">
            {children}
          </main>
        </ShowProvider>
      </body>
    </html>
  );
}
