import "./globals.css";
import Navbar from "./components/Navbar";
import { Nunito } from "next/font/google";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Banda Anistia",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/anistiaLogoTransparente.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <Navbar />
        <main className="h-screen flex justify-center items-center sm:items-start">
          {children}
        </main>
      </body>
    </html>
  );
}
