import "./globals.css";
import Navbar from "./_components/Navbar";
import { Nunito } from "next/font/google";
import { ShowProvider } from "./_context/ShowContext";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Banda Anistia",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/anistiaLogoTransparente.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth w-full" suppressHydrationWarning>
      <body className={`${nunito.className} text-sky-100 bg-black antialiased vsc-initialized`}>
        <Navbar />
        <ShowProvider>
          <main className="flex flex-col w-full mt-14 mb-24">
            {children}
          </main>
        </ShowProvider>
      </body>
    </html>
  );
}
